name: Auto Update Submodules

on:
  push:
    paths:
      - 'path/to/your/submodule/**'  # 监控子模块路径下的任何更改

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive  # 递归更新子模块

    - name: Check for submodule updates
      run: |
        git submodule update --remote --merge
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Auto-update submodules"
          git push origin ${{ github.ref }}
        fi
